<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">

<head>

<meta charset="utf-8" />
<meta name="generator" content="quarto-1.8.25" />

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />

<meta name="author" content="Nozimjon Ortiqov" />

<title>Family Background and Educational Attainment in Uzbekistan, 2010–2023</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<!-- htmldependencies:E3FAD763 -->

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <div id="quarto-toc-target"></div>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Family Background and Educational Attainment in Uzbekistan, 2010–2023</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nozimjon Ortiqov </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>

<nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract">Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#data-and-measurement" id="toc-data-and-measurement"><span class="header-section-number">2</span> Data and Measurement</a>
  <ul>
  <li><a href="#core-data" id="toc-core-data"><span class="header-section-number">2.1</span> Core Data</a></li>
  <li><a href="#education-measures" id="toc-education-measures"><span class="header-section-number">2.2</span> Education Measures</a></li>
  <li><a href="#mobility-outcomes" id="toc-mobility-outcomes"><span class="header-section-number">2.3</span> Mobility Outcomes</a></li>
  <li><a href="#summary-statistics" id="toc-summary-statistics"><span class="header-section-number">2.4</span> Summary Statistics</a></li>
  <li><a href="#covariates" id="toc-covariates"><span class="header-section-number">2.5</span> Covariates</a></li>
  <li><a href="#pandemic-mechanism-variables" id="toc-pandemic-mechanism-variables"><span class="header-section-number">2.6</span> Pandemic Mechanism Variables</a></li>
  </ul></li>
  <li><a href="#empirical-strategy" id="toc-empirical-strategy"><span class="header-section-number">3</span> Empirical Strategy</a>
  <ul>
  <li><a href="#module-a-mobility-levels-and-trends" id="toc-module-a-mobility-levels-and-trends"><span class="header-section-number">3.1</span> Module A: Mobility Levels and Trends</a></li>
  <li><a href="#module-b-correlates-of-mobility" id="toc-module-b-correlates-of-mobility"><span class="header-section-number">3.2</span> Module B: Correlates of Mobility</a></li>
  <li><a href="#module-c-pandemic-era-mechanisms" id="toc-module-c-pandemic-era-mechanisms"><span class="header-section-number">3.3</span> Module C: Pandemic-Era Mechanisms</a></li>
  </ul></li>
  <li><a href="#descriptive-results" id="toc-descriptive-results"><span class="header-section-number">4</span> Descriptive Results</a>
  <ul>
  <li><a href="#sample-composition-and-completeness" id="toc-sample-composition-and-completeness"><span class="header-section-number">4.1</span> Sample Composition and Completeness</a></li>
  <li><a href="#national-mobility-metrics-by-wave" id="toc-national-mobility-metrics-by-wave"><span class="header-section-number">4.2</span> National Mobility Metrics by Wave</a></li>
  <li><a href="#transition-structure" id="toc-transition-structure"><span class="header-section-number">4.3</span> Transition Structure</a></li>
  <li><a href="#descriptive-heterogeneity" id="toc-descriptive-heterogeneity"><span class="header-section-number">4.4</span> Descriptive Heterogeneity</a></li>
  </ul></li>
  <li><a href="#correlates-of-educational-mobility" id="toc-correlates-of-educational-mobility"><span class="header-section-number">5</span> Correlates of Educational Mobility</a>
  <ul>
  <li><a href="#pooled-persistence-trend-model" id="toc-pooled-persistence-trend-model"><span class="header-section-number">5.1</span> Pooled Persistence-Trend Model</a></li>
  <li><a href="#attainment-score-model" id="toc-attainment-score-model"><span class="header-section-number">5.2</span> Attainment-Score Model</a></li>
  <li><a href="#raw-versus-conditional-trend-interpretation" id="toc-raw-versus-conditional-trend-interpretation"><span class="header-section-number">5.3</span> Raw Versus Conditional Trend Interpretation</a></li>
  <li><a href="#upward-mobility-models" id="toc-upward-mobility-models"><span class="header-section-number">5.4</span> Upward Mobility Models</a></li>
  <li><a href="#heterogeneity-in-persistence" id="toc-heterogeneity-in-persistence"><span class="header-section-number">5.5</span> Heterogeneity in Persistence</a></li>
  <li><a href="#household-support-environment-from-hbs" id="toc-household-support-environment-from-hbs"><span class="header-section-number">5.6</span> Household Support Environment from HBS</a></li>
  <li><a href="#household-support-by-university-expansion-intensity" id="toc-household-support-by-university-expansion-intensity"><span class="header-section-number">5.7</span> Household Support by University-Expansion Intensity</a></li>
  </ul></li>
  <li><a href="#pandemic-era-disruption" id="toc-pandemic-era-disruption"><span class="header-section-number">6</span> Pandemic-Era Disruption</a>
  <ul>
  <li><a href="#sample-and-disruption-profile" id="toc-sample-and-disruption-profile"><span class="header-section-number">6.1</span> Sample and Disruption Profile</a></li>
  <li><a href="#main-module-c-takeaway" id="toc-main-module-c-takeaway"><span class="header-section-number">6.2</span> Main Module C Takeaway</a></li>
  </ul></li>
  <li><a href="#discussion-and-conclusion" id="toc-discussion-and-conclusion"><span class="header-section-number">7</span> Discussion and Conclusion</a></li>
  <li><a href="#bibliography" id="toc-bibliography">References</a></li>
  </ul>
</nav>
<section id="abstract" class="level2 unnumbered">
<h2 class="unnumbered">Abstract</h2>
<p>Uzbekistan has nearly doubled the number of higher education institutions since 2017, yet no multi-wave evidence exists on whether family background is losing its grip on educational attainment. This paper uses the Life in Transition Survey for 2010, 2016, and 2022-23 to provide the first three-wave profile of intergenerational educational mobility in the country. The rank-rank persistence slope rises from 0.134 in 2010 to 0.307 in 2016 (p = &lt;0.001) and stands at 0.252 in 2022-23. Parental education is the strongest and most stable predictor of attainment across nested pooled specifications; in 2022-23, 87.3 percent of respondents from university-educated families also reached university. A child-module extension documents widespread pandemic-era learning disruption and heavy reliance on maternal support, but no clear gap in education stoppage by parental education. Expanding formal access has not yet weakened the link between family background and schooling outcomes.</p>
<p><strong>Keywords:</strong> intergenerational mobility, educational attainment, Uzbekistan, Life in Transition Survey, rank-rank slope</p>
<p><strong>JEL codes:</strong> I24, I26, J62, P36</p>
</section>
<section id="introduction" class="level2" data-number="1">
<h2 data-number="1"><span class="header-section-number">1</span> Introduction</h2>
<p>Between 2017 and 2024, Uzbekistan nearly doubled the number of higher education institutions (from 119 to 222) and tripled enrolled students from roughly 441,000 to over 1.4 million <span class="citation" data-cites="uzb_admin_he_2025">(<a href="#ref-uzb_admin_he_2025" role="doc-biblioref">Statistical Agency under the President of the Republic of Uzbekistan 2025</a>)</span>. This expansion, layered onto three decades of post-Soviet market transition, raises a question that the country’s own evidence base cannot yet answer: has broader access weakened the link between parental education and children’s attainment, or does family background retain its grip even as formal opportunity expands?</p>
<p>This paper uses the Life in Transition Survey (LiTS) for 2010, 2016, and 2022-23 to provide the first multi-wave profile of intergenerational educational mobility in Uzbekistan. The rank-rank persistence slope — the within-wave gradient between respondent and parental education rank — rises from 0.134 in 2010 to 0.307 in 2016, a statistically significant increase (p = &lt;0.001). The 2022-23 slope is 0.252. These values place Uzbekistan in the moderate-to-high range for developing countries; Hertz et al. <span class="citation" data-cites="hertz_2008">(<a href="#ref-hertz_2008" role="doc-biblioref">2008</a>)</span> report intergenerational education correlations spanning 0.20 to 0.60 across settings. Parental education is the strongest and most stable predictor across all pooled specifications, and the nested model structure shows that adding demographic and household controls does not weaken that association. To put the 2016 slope in concrete terms: at 0.307, a child whose parents sit at the 25th percentile of the educational distribution is predicted to reach the 42th percentile of own education, compared to the 58th percentile for a child at the 75th parental percentile. The implied gap is roughly 15 percentile points. A child-module extension from the 2022-23 wave documents widespread pandemic-era learning disruption and heavy reliance on maternal support, but finds no robust parental-education gap in education stoppage.</p>
<p>The paper uses a pre-specified (“locked”) bundle of measures: a rank-rank slope, upward mobility, downward mobility, and same-category persistence, held constant across all waves and specifications. Category-based rates preserve substantive interpretability; rank-based measures are better suited to cross-wave comparison because they locate respondents within each wave’s distribution and are less sensitive to aggregate educational expansion <span class="citation" data-cites="torche_2015 weide_etal_2024 stromberg_engzell_2025">(<a href="#ref-torche_2015" role="doc-biblioref">Torche 2015</a>; <a href="#ref-weide_etal_2024" role="doc-biblioref">Weide et al. 2024</a>; <a href="#ref-stromberg_engzell_2025" role="doc-biblioref">Strömberg and Engzell 2025</a>)</span>. This dual approach matters because no single statistic fully describes opportunity, and recent evidence shows that cross-country mobility rankings shift with coding choices and sample definitions <span class="citation" data-cites="torche_2015">(<a href="#ref-torche_2015" role="doc-biblioref">Torche 2015</a>)</span>.</p>
<p>Comparative evidence on intergenerational educational mobility is extensive, but it leaves a clear gap for Uzbekistan. Cross-country studies document three regularities: mobility varies widely and does not converge mechanically with development; many developing settings display lower mobility than richer economies even after expansion; and rising access does not automatically weaken family-background gradients at upper schooling levels <span class="citation" data-cites="hertz_2008 narayan_etal_2018 weide_etal_2024 emran_shilpi_2015">(<a href="#ref-hertz_2008" role="doc-biblioref">Hertz et al. 2008</a>; <a href="#ref-narayan_etal_2018" role="doc-biblioref">Narayan et al. 2018</a>; <a href="#ref-weide_etal_2024" role="doc-biblioref">Weide et al. 2024</a>; <a href="#ref-emran_shilpi_2015" role="doc-biblioref">Emran and Shilpi 2015</a>)</span>. Post-socialist economies show no single mobility path; common Soviet legacies do not determine later outcomes <span class="citation" data-cites="verashchagina_2012">(<a href="#ref-verashchagina_2012" role="doc-biblioref">Verashchagina 2012</a>)</span>. Kyrgyzstan is the closest Central Asian comparator in the published literature <span class="citation" data-cites="bruck_esenaliev_2018">(<a href="#ref-bruck_esenaliev_2018" role="doc-biblioref">Brück and Esenaliev 2018</a>)</span>, and Turkey provides a useful benchmark because it combines middle-income status with strong spatial disparities in school availability <span class="citation" data-cites="aydemir_yazici_2019">(<a href="#ref-aydemir_yazici_2019" role="doc-biblioref">Aydemir and Yazici 2019</a>)</span>. Both cases show that mobility is higher where schooling opportunity and household resources are stronger, which motivates this paper’s attention to regional, cohort, and place-based heterogeneity.</p>
<p>For Uzbekistan specifically, the evidence base remains weighted toward sector diagnostics and policy discussion. World Bank and UNICEF reports point to persistent disparities across region, location, gender, tertiary pathways, and household learning environments <span class="citation" data-cites="wb_uzb_2018 unicef_sitan_2020 unicef_sitan_2024 wb_gender_2024">(<a href="#ref-wb_uzb_2018" role="doc-biblioref">World Bank 2018</a>, <a href="#ref-wb_gender_2024" role="doc-biblioref">2024</a>; <a href="#ref-unicef_sitan_2020" role="doc-biblioref">UNICEF Uzbekistan 2020</a>, <a href="#ref-unicef_sitan_2024" role="doc-biblioref">2024</a>)</span>, and analysis of the higher-education system identifies long-standing constraints in access, quality, governance, and labor-market relevance <span class="citation" data-cites="wb_modernizing_tertiary_2017">(<a href="#ref-wb_modernizing_tertiary_2017" role="doc-biblioref">World Bank 2017</a>)</span>. These sources establish why parental education, regional conditions, and household support capacity are plausible correlates of mobility, but they are not mobility designs. Where bottlenecks remain strongest at advanced levels of schooling, intergenerational persistence can survive even as basic and secondary participation rise. Since 2017, a broad reform cycle (preschool expansion, sector restructuring, widened tertiary access) has reshaped the education system <span class="citation" data-cites="wb_uzb_2018 unicef_compact_2024 unicef_sitan_2024">(<a href="#ref-wb_uzb_2018" role="doc-biblioref">World Bank 2018</a>; <a href="#ref-unicef_compact_2024" role="doc-biblioref">UNICEF 2024</a>; <a href="#ref-unicef_sitan_2024" role="doc-biblioref">UNICEF Uzbekistan 2024</a>)</span>. This paper does not attribute observed mobility patterns to reforms; it treats reform as context that sharpens interpretation.</p>
<p>The claims throughout are descriptive and associational. Module A documents levels and trends. Module B estimates conditional associations using pooled models with region, cohort, and wave fixed effects. Module C provides bounded non-causal evidence on pandemic-era household learning conditions. This belongs to the descriptive measurement strand of the mobility literature rather than to the causal identification strand that exploits exogenous variation across place, cohort, or policy exposure <span class="citation" data-cites="urbina_2018 akarcay_polat_2017">(<a href="#ref-urbina_2018" role="doc-biblioref">Urbina 2018</a>; <a href="#ref-akarcay_polat_2017" role="doc-biblioref">Akarçay-Gürbüz and Polat 2017</a>)</span>. The relevant pandemic literature, on unequal burdens of school closures and household substitution for formal instruction, justifies asking whether lower-parent-education households report greater disruption, but the LiTS IV child module is a small cross-sectional subsample and does not support a causal account <span class="citation" data-cites="alam_tiwari_2020 munoz_najar_etal_2021 iqbal_patrinos_2025">(<a href="#ref-alam_tiwari_2020" role="doc-biblioref">Alam and Tiwari 2020</a>; <a href="#ref-munoz_najar_etal_2021" role="doc-biblioref">Muñoz-Najar et al. 2021</a>; <a href="#ref-iqbal_patrinos_2025" role="doc-biblioref">Iqbal and Patrinos 2025</a>)</span>.</p>
<p>Section 2 describes the data and measurement choices, Section 3 lays out the empirical strategy, Sections 4 through 6 present the descriptive, associational, and pandemic-disruption results, and Section 7 discusses the findings and their implications.</p>
</section>
<section id="data-and-measurement" class="level2" data-number="2">
<h2 data-number="2"><span class="header-section-number">2</span> Data and Measurement</h2>
<section id="core-data" class="level3" data-number="2.1">
<h3 data-number="2.1"><span class="header-section-number">2.1</span> Core Data</h3>
<p>The main source is the Life in Transition Survey (LiTS) for 2010, 2016, and 2022-23. These are repeated cross-sections, not a panel: changes over time reflect shifts in population-level patterns rather than changes within fixed families. The surveys provide comparable information on respondents’ own education, parental education, age, sex, and place of residence. Regional labels are harmonized with a fixed cross-wave mapping before pooled estimation; regional coverage still differs by wave, so regional results are interpreted as composition-conditional, not as fully balanced panel comparisons.</p>
<p>The analytical sample restricts to respondents aged 25-64 so that own education is largely complete. Cohorts are grouped as 25-34, 35-44, 45-54, and 55-64. The analysis uses weighted estimates throughout and suppresses subgroup outputs when the valid cell size falls below 30.</p>
<p>A second data source, the Household Budget Survey, provides supplementary context on household structure, migration, schooling expenses, tutoring, and internet access. Because direct parent-child linkage in HBS is only partially supported in the current audit, it is not the source of the intergenerational estimates reported here.</p>
</section>
<section id="education-measures" class="level3" data-number="2.2">
<h3 data-number="2.2"><span class="header-section-number">2.2</span> Education Measures</h3>
<p>The paper uses two measurement families built from a common harmonization step. LiTS parental-schooling responses vary across waves in wording and granularity, so all observed mother and father responses are first mapped onto a common six-category ladder: no formal education, primary, lower secondary, upper secondary, post-secondary non-tertiary, and tertiary. The implied years follow the project mapping in Appendix C1: 0, 6, 9, 11, 13, and 16 years. In Modules A and B, when both parents are observed, the analysis uses the higher reported category as the parental education measure; when only one parent is available, the observed value is retained. This max-parent rule keeps the intergenerational comparison consistent across waves while limiting attrition from asymmetric parental reporting, but it does not separate maternal and paternal channels or the contribution of assortative mating between parents.</p>
<p>Module C is narrower. It uses the mean of observed mother and father years for the low-versus-high split, because a weighted median split built on the max-parent proxy would set the threshold at 16.0 years and leave only 0 observations in the higher-parent group. Appendix D2 shows that the rank-based national series is stable under alternative parent constructions. A harmonization-specific check that replaces the back-converted 2010 max-parent years with observed parental years yields a 2010 slope of 0.131 instead of 0.134, while the 2016 and 2022-23 slopes are unchanged to three decimals. Category-based rates are more sensitive to whether the parent proxy uses the maximum, an average, or a single observed parent. The Module C split is a within-module partition, not a continuation of the max-parent gradient used in Modules A and B.</p>
<p>The harmonized ladder supports two complementary measures. An ordered education score enters category-based mobility rates and pooled attainment regressions. A within-wave weighted percentile rank enters the rank-rank persistence models. The category-based outcomes preserve the intuitive language of upward mobility, downward mobility, and same-category persistence. The rank-based outcomes are better suited to cross-wave comparison because they are less sensitive to questionnaire differences and to aggregate educational expansion. Reporting both is deliberate: one family preserves substantive interpretability, while the other provides the preferred cross-wave benchmark.</p>
</section>
<section id="mobility-outcomes" class="level3" data-number="2.3">
<h3 data-number="2.3"><span class="header-section-number">2.3</span> Mobility Outcomes</h3>
<p>Four outcomes are measured:</p>
<ul>
<li>Rank-rank slope: the relationship between own education rank and parental education rank within each wave.</li>
<li>Upward mobility: an indicator that own education exceeds parental education.</li>
<li>Downward mobility: an indicator that own education is lower than parental education.</li>
<li>Persistence: an indicator that own education remains at the same category as parental education.</li>
</ul>
<p>The paper reports these measures nationally and, where the denominator permits, by subgroup.</p>
</section>
<section id="summary-statistics" class="level3" data-number="2.4">
<h3 data-number="2.4"><span class="header-section-number">2.4</span> Summary Statistics</h3>
<p><a href="#tbl-summary-stats" class="quarto-xref">Table 1</a> reports the key variables by wave. Own and parental education years both rise across waves, reflecting both compositional shifts and expansion. The 2022-23 wave has a smaller sample and a higher female share in the unweighted data, though survey weights correct this for estimation.</p>
<div class="cell">
<div id="tbl-summary-stats" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 1: Summary statistics for the analytical sample by LiTS wave.
</figcaption>
<div aria-describedby="tbl-summary-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top">
<colgroup>
<col style="width: 9%" />
<col style="width: 5%" />
<col style="width: 25%" />
<col style="width: 31%" />
<col style="width: 13%" />
<col style="width: 8%" />
<col style="width: 6%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Wave</th>
<th style="text-align: right;">N</th>
<th style="text-align: left;">Own education (years)</th>
<th style="text-align: left;">Parental education (years)</th>
<th style="text-align: left;">Age</th>
<th style="text-align: left;">Female</th>
<th style="text-align: left;">Urban</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2010</td>
<td style="text-align: right;">1125</td>
<td style="text-align: left;">11.4 (2.3)</td>
<td style="text-align: left;">10.8 (3.1)</td>
<td style="text-align: left;">40.8 (10.5)</td>
<td style="text-align: left;">61.2%</td>
<td style="text-align: left;">33.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">2016</td>
<td style="text-align: right;">1239</td>
<td style="text-align: left;">13.1 (2.7)</td>
<td style="text-align: left;">12.7 (3.1)</td>
<td style="text-align: left;">43.9 (11.2)</td>
<td style="text-align: left;">54.7%</td>
<td style="text-align: left;">41.7%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2022-23</td>
<td style="text-align: right;">791</td>
<td style="text-align: left;">14.7 (2.3)</td>
<td style="text-align: left;">14.1 (2.7)</td>
<td style="text-align: left;">41.1 (10.9)</td>
<td style="text-align: left;">66.8%</td>
<td style="text-align: left;">36.7%</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Notes: Means with standard deviations in parentheses. Parental education uses the max-parent harmonized years. Female and urban shares are unweighted. The 2010 wave uses back-converted parental years from the continuous question (q718/q719); 2016 and 2022-23 use direct categorical responses mapped to the locked six-category ladder.</p>
</section>
<section id="covariates" class="level3" data-number="2.5">
<h3 data-number="2.5"><span class="header-section-number">2.5</span> Covariates</h3>
<p>The pooled correlates models are estimated as a nested sequence. All specifications include region, cohort, and wave fixed effects. The minimal specification includes only the parental education term or interaction of interest. The demographic specification adds two clearly pre-determined controls, urban residence and female. The extended specification then adds current household variables that pass the project’s coverage screen. A candidate extended control must be non-missing for at least 20 percent of the pooled sample, non-missing for at least 10 percent of observations in every wave, and take at least two distinct observed values. The extended controls that survive this gate are reported as sensitivity variables, not clean pre-treatment adjustments; the household income proxy is available only in the 2016 and 2022-23 waves and is excluded by the wave-specific coverage rule when all three waves enter the pooled sample.</p>
<p>For pooled inference, the implemented regressions cluster standard errors at the region level. The harmonized LiTS files retain a stable region identifier across waves, but no harmonized PSU variable is constructed in the pooled analysis files, so region clustering is the implemented fallback.</p>
<p>Because those pooled models rely on only 10 region clusters in 2010 and 2016 and 14 in 2022-23, Appendix D4 also reports Webb wild-cluster-bootstrap p-values alongside the conventional region-clustered p-values for the main persistence-trend comparisons. Throughout the paper, bootstrap <span class="math inline">\(p \leq 0.05\)</span> is described as statistically distinguishable, <span class="math inline">\(0.05 &lt; p \leq 0.10\)</span> as suggestive, and <span class="math inline">\(p &gt; 0.10\)</span> as imprecise. No omnibus multiple-testing correction is applied across the full family of subgroup and appendix checks, so those results are used as structured corroboration, not standalone discovery claims.</p>
</section>
<section id="pandemic-mechanism-variables" class="level3" data-number="2.6">
<h3 data-number="2.6"><span class="header-section-number">2.6</span> Pandemic Mechanism Variables</h3>
<p>From the 2022-23 LiTS child module, the paper constructs descriptive indicators for remote-learning disruption, learning support, and home-learning constraints. These include switching to online learning, switching to hybrid learning, education stopping during COVID, school closure without online learning, shared-device use, support from mother, father, or relatives, and indicators for internet, device, cost, and time-balance challenges.</p>
<p>The mechanism sample is much smaller than the full LiTS IV sample. The child-module flow moves from 1006 Uzbekistan respondents in LiTS IV to 650 with child-module eligibility information, 186 with a child enrolled before COVID, and 183 with non-missing parental schooling. The extension illustrates patterns rather than supporting broad generalization.</p>
</section>
</section>
<section id="empirical-strategy" class="level2" data-number="3">
<h2 data-number="3"><span class="header-section-number">3</span> Empirical Strategy</h2>
<p>The empirical strategy has three modules and uses one compact notation throughout. Let <span class="math inline">\(Y_{iw}\)</span> denote respondent <span class="math inline">\(i\)</span>’s educational outcome in wave <span class="math inline">\(w\)</span>, and let <span class="math inline">\(P_{iw}\)</span> denote parental education measured on the corresponding scale. In Module A, <span class="math inline">\(Y_{iw}\)</span> and <span class="math inline">\(P_{iw}\)</span> are within-wave education ranks. In Module B, <span class="math inline">\(Y_i\)</span> alternates across respondent rank, the harmonized education score, an indicator for upward mobility, and an indicator for same-category persistence; <span class="math inline">\(P_i\)</span> likewise denotes parental rank, the parental education score, or a set of parental education-category indicators. <span class="math inline">\(U_i\)</span> and <span class="math inline">\(F_i\)</span> indicate urban residence and female, <span class="math inline">\(X_i\)</span> collects migration exposure and multigenerational household structure, <span class="math inline">\(D_{ti}\)</span> is a wave indicator for <span class="math inline">\(t \in \{2016, 2022\}\)</span> with 2010 as the omitted category, and <span class="math inline">\(\mu_r\)</span>, <span class="math inline">\(\lambda_c\)</span>, and <span class="math inline">\(\tau_w\)</span> denote region, cohort, and wave effects. In Module C, <span class="math inline">\(L_i\)</span> indicates low parental education.</p>
<section id="module-a-mobility-levels-and-trends" class="level3" data-number="3.1">
<h3 data-number="3.1"><span class="header-section-number">3.1</span> Module A: Mobility Levels and Trends</h3>
<p>The first module estimates national mobility levels by wave using the rank-rank framework widely adopted in the intergenerational mobility literature <span class="citation" data-cites="chetty_etal_2014">(e.g., <a href="#ref-chetty_etal_2014" role="doc-biblioref">Chetty et al. 2014</a>)</span>. Its core descriptive specification is:</p>
<p><span class="math display">\[
Y_{iw} = \alpha_w + \beta_w P_{iw} + \varepsilon_{iw}
\]</span></p>
<p>where <span class="math inline">\(Y_{iw}\)</span> and <span class="math inline">\(P_{iw}\)</span> are respondent and parental education ranks within wave <span class="math inline">\(w\)</span>. The coefficient <span class="math inline">\(\beta_w\)</span> is the within-wave persistence slope: larger values imply that respondent rank tracks parental rank more closely and therefore signal lower relative mobility. The same module also reports weighted rates of upward mobility, downward mobility, and same-category persistence on the harmonized categorical scale.</p>
<p>For this descriptive module, uncertainty is reported from the weighted within-wave OLS fits directly. The more formal cross-wave inference is delegated to the pooled Module B specifications and their region-clustered standard errors.</p>
</section>
<section id="module-b-correlates-of-mobility" class="level3" data-number="3.2">
<h3 data-number="3.2"><span class="header-section-number">3.2</span> Module B: Correlates of Mobility</h3>
<p>The second module estimates pooled correlates models with region, cohort, and wave fixed effects. Its pooled benchmark is:</p>
<p><span class="math display">\[
Y_i
= \alpha + \beta P_i
+ \sum_{t \in \{2016, 2022\}} \theta_t \left(P_i \times D_{ti}\right)
+ \rho_1 U_i + \rho_2 F_i + X_i&#39; \gamma + \mu_r + \lambda_c + \tau_w + \varepsilon_i
\]</span></p>
<p><a href="#tbl-spec-map" class="quarto-xref">Table 2</a> summarizes how the pooled equation maps onto each specification. Throughout, coefficients are interpreted as conditional associations rather than causal effects.</p>
<div class="cell">
<div id="tbl-spec-map" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-spec-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 2: Module B specification map.
</figcaption>
<div aria-describedby="tbl-spec-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top">
<colgroup>
<col style="width: 21%" />
<col style="width: 22%" />
<col style="width: 18%" />
<col style="width: 37%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Label</th>
<th style="text-align: left;">Outcome (<span class="math inline">\(Y_i\)</span>)</th>
<th style="text-align: left;">Parental term (<span class="math inline">\(P_i\)</span>)</th>
<th style="text-align: left;">Key variation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Eq. 2: Persistence trend</td>
<td style="text-align: left;">Respondent rank</td>
<td style="text-align: left;">Parental rank</td>
<td style="text-align: left;"><span class="math inline">\(\theta_t\)</span>: wave × parent rank interaction</td>
</tr>
<tr class="even">
<td style="text-align: left;">Eq. 3: Attainment score</td>
<td style="text-align: left;">Harmonized education score</td>
<td style="text-align: left;">Parental education score</td>
<td style="text-align: left;"><span class="math inline">\(\beta\)</span>: conditional parental association</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Eq. 4: Upward mobility</td>
<td style="text-align: left;">Indicator: own &gt; parental category</td>
<td style="text-align: left;">Parental category indicators</td>
<td style="text-align: left;">Category-specific transition probabilities</td>
</tr>
<tr class="even">
<td style="text-align: left;">Eq. 5: Persistence heterogeneity</td>
<td style="text-align: left;">Indicator: own = parental category</td>
<td style="text-align: left;">Parental education score</td>
<td style="text-align: left;"><span class="math inline">\(P_i \times U_i\)</span>, <span class="math inline">\(P_i \times F_i\)</span>, <span class="math inline">\(P_i \times D_{2022}\)</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Notes: All specifications include region, cohort, and wave fixed effects. Nested control sets: minimal (parental term + FE only), demographic (+ urban, female), extended (+ migration exposure, multigenerational household). Appendix D6 also reports a low-parent subsample variant of Eq. 4 as an exploratory sensitivity.</p>
</section>
<section id="module-c-pandemic-era-mechanisms" class="level3" data-number="3.3">
<h3 data-number="3.3"><span class="header-section-number">3.3</span> Module C: Pandemic-Era Mechanisms</h3>
<p>The third module uses the 2022-23 child module to document disruption and household-support patterns by parental education group. The main text reports weighted outcome rates and low-versus-high parental-education splits. Adjusted region-fixed-effects logits appear only in the appendix because split support is unstable under stricter thresholds and alternative parent proxies. Those appendix logits include low parental education, urban residence, and their interaction with region fixed effects; they omit gender and the broader Module B control set to keep the diagnostic layer parsimonious, and they are estimated only when each group contains at least 15 observations with sufficient event variation.</p>
</section>
</section>
<section id="descriptive-results" class="level2" data-number="4">
<h2 data-number="4"><span class="header-section-number">4</span> Descriptive Results</h2>
<section id="sample-composition-and-completeness" class="level3" data-number="4.1">
<h3 data-number="4.1"><span class="header-section-number">4.1</span> Sample Composition and Completeness</h3>
<p><a href="#tbl-sample-composition" class="quarto-xref">Table 3</a> reports the analytical base by wave. The age-restricted Uzbekistan LiTS samples contain 1,125 respondents in 2010, 1,239 in 2016, and 791 in 2022-23. The 2022-23 wave is somewhat more female in the unweighted analytical sample, although the weighted estimation sample is much closer to balanced, while the cohort mix remains centered on the younger and middle adult cohorts in all three surveys.</p>
<p>Parental-education missingness is not uniform across waves. After harmonization, respondents’ own education is fully observed in all three waves, while weighted parental-education missingness is 17.3 percent in 2010, 4.3 percent in 2016, and 0.8 percent in 2022-23. Missing-parent cases are older and somewhat less educated in 2010 and 2016: the weighted age gap is about 2.321 years in 2010 and 7.529 years in 2016, while the weighted own-schooling gap is about -0.339 and -1.439 years, respectively. Missingness therefore threatens level comparability most clearly in the earliest wave. Parental education is also retrospectively reported, so recall error and the coarse category-to-years harmonization in 2010 can attenuate the observed slope toward zero.</p>
<div class="cell">
<div id="tbl-sample-composition" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sample-composition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 3: Analytical sample composition and completeness by LiTS wave.
</figcaption>
<div aria-describedby="tbl-sample-composition-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top" style="width:100%;">
<colgroup>
<col style="width: 5%" />
<col style="width: 5%" />
<col style="width: 9%" />
<col style="width: 9%" />
<col style="width: 33%" />
<col style="width: 16%" />
<col style="width: 19%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Wave</th>
<th style="text-align: left;">Valid N</th>
<th style="text-align: left;">Female share</th>
<th style="text-align: left;">Urban share</th>
<th style="text-align: left;">Cohort shares (25-34 / 35-44 / 45-54 / 55-64)</th>
<th style="text-align: left;">Own education missing</th>
<th style="text-align: left;">Parental education missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2010</td>
<td style="text-align: left;">1,125</td>
<td style="text-align: left;">61.2 percent</td>
<td style="text-align: left;">33.7 percent</td>
<td style="text-align: left;">33.5 / 30.2 / 23.3 / 13.0</td>
<td style="text-align: left;">0.0 percent</td>
<td style="text-align: left;">18.7 percent</td>
</tr>
<tr class="even">
<td style="text-align: left;">2016</td>
<td style="text-align: left;">1,239</td>
<td style="text-align: left;">54.7 percent</td>
<td style="text-align: left;">41.7 percent</td>
<td style="text-align: left;">25.6 / 26.6 / 24.5 / 23.2</td>
<td style="text-align: left;">0.0 percent</td>
<td style="text-align: left;">4.4 percent</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2022-23</td>
<td style="text-align: left;">791</td>
<td style="text-align: left;">66.8 percent</td>
<td style="text-align: left;">36.7 percent</td>
<td style="text-align: left;">32.7 / 29.1 / 23.5 / 14.7</td>
<td style="text-align: left;">0.0 percent</td>
<td style="text-align: left;">1.9 percent</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Notes: Valid N is the age-25-64 Uzbekistan analytical sample in each wave. Female and urban shares are unweighted analytical-sample shares, while the missingness columns report the share of respondents with missing own or parental education in the harmonized wave files.</p>
<p><a href="#tbl-sample-composition" class="quarto-xref">Table 3</a> combines the published Tier A sample and completeness outputs with simple analytical-sample composition shares from the harmonized LiTS file. Appendix D3 adds missing-versus-observed diagnostics and simple sensitivity checks. A wave-by-cohort-by-sex-by-urban mode-imputation sensitivity moves the national rank-rank slopes to 0.116, 0.290, and 0.252, while even the extreme all-low and all-high assignments preserve the same wave ordering of the national slopes. Parental-education missingness widens uncertainty around levels, especially in 2010, but does not mechanically create the 2016 peak.</p>
</section>
<section id="national-mobility-metrics-by-wave" class="level3" data-number="4.2">
<h3 data-number="4.2"><span class="header-section-number">4.2</span> National Mobility Metrics by Wave</h3>
<p><a href="#tbl-mobility-metrics" class="quarto-xref">Table 4</a> reports the paper’s core national mobility measures in a by-wave layout. The rank-rank slope rises from <strong>0.134</strong> in 2010 to <strong>0.307</strong> in 2016 and is <strong>0.252</strong> in 2022-23; the corresponding 95 percent confidence intervals are [0.076, 0.192], [0.254, 0.359], and [0.195, 0.310]. The formal raw slope-difference test shows a statistically clear increase from 2010 to 2016 of 0.172 (p = &lt;0.001), but a 2016-to-2022 change of only -0.054 (p = 0.173). Category-based rates tell a similar broad story, with persistence rising and downward mobility falling in the later waves.</p>
<p>The harmonized denominator is now aligned across the rank and category measures within each wave. In 2022-23, both the rank-rank slope and the category-based rates rely on 776 valid observations. The main caution is inferential, not mechanical: the 2022 national estimates remain noisier than the 2016 values, and several subgroup or regional intervals are wide.</p>
<p>Regional composition matters more for the 2022 comparison than for the earlier waves. When the descriptive series is restricted to the 10 regions that contribute valid rank support in all three waves, the 2010 and 2016 slopes remain 0.134 and 0.307, but the 2022 slope rises to 0.281 from 0.252 in the full sample. Its common-region 95 percent interval is [0.208, 0.353]. Appendix D5 shows that the companion 2022 transition matrix also shifts under this balanced-region support restriction. The post-2016 flattening is partly composition-conditional rather than a fully balanced geographic comparison.</p>
<div class="cell">
<div id="tbl-mobility-metrics" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mobility-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 4: National mobility metrics by LiTS wave.
</figcaption>
<div aria-describedby="tbl-mobility-metrics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top">
<colgroup>
<col style="width: 9%" />
<col style="width: 28%" />
<col style="width: 18%" />
<col style="width: 20%" />
<col style="width: 14%" />
<col style="width: 9%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Wave</th>
<th style="text-align: left;">Rank-rank slope (95% CI)</th>
<th style="text-align: left;">Upward mobility</th>
<th style="text-align: left;">Downward mobility</th>
<th style="text-align: left;">Persistence</th>
<th style="text-align: left;">Valid N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2010</td>
<td style="text-align: left;">0.134 [0.076, 0.192]</td>
<td style="text-align: left;">31.1 percent</td>
<td style="text-align: left;">25.9 percent</td>
<td style="text-align: left;">43.0 percent</td>
<td style="text-align: left;">913</td>
</tr>
<tr class="even">
<td style="text-align: left;">2016</td>
<td style="text-align: left;">0.307 [0.254, 0.359]</td>
<td style="text-align: left;">25.6 percent</td>
<td style="text-align: left;">18.2 percent</td>
<td style="text-align: left;">56.3 percent</td>
<td style="text-align: left;">1,185</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2022-23</td>
<td style="text-align: left;">0.252 [0.195, 0.310]</td>
<td style="text-align: left;">24.6 percent</td>
<td style="text-align: left;">8.1 percent</td>
<td style="text-align: left;">67.3 percent</td>
<td style="text-align: left;">776</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Notes: Rank-rank slopes are within-wave survey-weighted OLS slopes of respondent rank on parental rank with analytic 95 percent confidence intervals. Upward, downward, and persistence rates are weighted category-based shares computed on the same valid parent-child denominator within each wave.</p>
<p><a href="#tbl-mobility-metrics" class="quarto-xref">Table 4</a> and <a href="#fig-rank-rank" class="quarto-xref">Figure 1</a> and <a href="#fig-directional-rates" class="quarto-xref">Figure 2</a> tell the same high-level story: educational persistence is substantial in every wave, the statistically clear descriptive increase occurs between 2010 and 2016, and the 2022-23 profile remains more persistent than the 2010 baseline without clearly exceeding the 2016 peak once uncertainty is shown.</p>
<div id="fig-rank-rank" class="quarto-float quarto-figure quarto-figure-center" alt="Rank-rank slope by LiTS wave.">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-rank-rank-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../outputs/figures/tier_a_rank_rank_by_wave.png" class="img-fluid" alt="Rank-rank slope by LiTS wave." />
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rank-rank-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 1: Rank-rank slope by LiTS wave.
</figcaption>
</figure>
</div>
<div id="fig-directional-rates" class="quarto-float quarto-figure quarto-figure-center" alt="Directional mobility rates by LiTS wave.">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-directional-rates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../outputs/figures/tier_a_directional_rates_by_wave.png" class="img-fluid" alt="Directional mobility rates by LiTS wave." />
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-directional-rates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 2: Directional mobility rates by LiTS wave.
</figcaption>
</figure>
</div>
</section>
<section id="transition-structure" class="level3" data-number="4.3">
<h3 data-number="4.3"><span class="header-section-number">4.3</span> Transition Structure</h3>
<p>The by-wave rates are easier to interpret alongside the transition structure in <a href="#tbl-transition-structure" class="quarto-xref">Table 5</a>. In both 2010 and 2016, respondents from lower-secondary and primary parental origins most often reach upper secondary, while respondents from upper-secondary parental origins remain concentrated in the same category. The pattern fits a system that permits some upward movement from lower origins but still exhibits strong persistence around the upper-secondary category that dominates the analytical sample.</p>
<p>The 2022-23 transition matrix remains thin at the lowest parental origins, but it is no longer confined to a single usable row. The tertiary parental-origin row shows 87.3 percent same-category persistence out of 500 valid cases, while the upper-secondary parental-origin row shows 63.0 percent movement into tertiary and 36.4 percent same-category persistence out of 263 valid cases. The transition evidence reinforces strong persistence at the top of the ladder; lower-origin 2022 rows remain too sparse for fine-grained inference.</p>
<div class="cell">
<div id="tbl-transition-structure" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-transition-structure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 5: Transition structure for parental-origin categories with usable cell counts.
</figcaption>
<div aria-describedby="tbl-transition-structure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top">
<colgroup>
<col style="width: 5%" />
<col style="width: 17%" />
<col style="width: 14%" />
<col style="width: 22%" />
<col style="width: 22%" />
<col style="width: 17%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Wave</th>
<th style="text-align: left;">Parental origin</th>
<th style="text-align: left;">Own: Primary</th>
<th style="text-align: left;">Own: Lower secondary</th>
<th style="text-align: left;">Own: Upper secondary</th>
<th style="text-align: left;">Parent-origin N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2010</td>
<td style="text-align: left;">Primary</td>
<td style="text-align: left;">2.8 percent</td>
<td style="text-align: left;">20.5 percent</td>
<td style="text-align: left;">64.8 percent</td>
<td style="text-align: left;">47</td>
</tr>
<tr class="even">
<td style="text-align: left;">2010</td>
<td style="text-align: left;">Lower secondary</td>
<td style="text-align: left;">0.6 percent</td>
<td style="text-align: left;">25.6 percent</td>
<td style="text-align: left;">60.7 percent</td>
<td style="text-align: left;">231</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2010</td>
<td style="text-align: left;">Upper secondary</td>
<td style="text-align: left;">0.0 percent</td>
<td style="text-align: left;">18.4 percent</td>
<td style="text-align: left;">68.6 percent</td>
<td style="text-align: left;">412</td>
</tr>
<tr class="even">
<td style="text-align: left;">2016</td>
<td style="text-align: left;">Primary</td>
<td style="text-align: left;">0.0 percent</td>
<td style="text-align: left;">14.2 percent</td>
<td style="text-align: left;">56.1 percent</td>
<td style="text-align: left;">39</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2016</td>
<td style="text-align: left;">Lower secondary</td>
<td style="text-align: left;">0.0 percent</td>
<td style="text-align: left;">17.1 percent</td>
<td style="text-align: left;">49.6 percent</td>
<td style="text-align: left;">187</td>
</tr>
<tr class="even">
<td style="text-align: left;">2016</td>
<td style="text-align: left;">Upper secondary</td>
<td style="text-align: left;">0.0 percent</td>
<td style="text-align: left;">6.0 percent</td>
<td style="text-align: left;">64.2 percent</td>
<td style="text-align: left;">428</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Notes: Entries are weighted shares within each parental-origin row. Rows with fewer than 30 valid cases are suppressed, which is why the main table focuses on the better-supported 2010 and 2016 rows and discusses the thinner 2022 structure in text.</p>
</section>
<section id="descriptive-heterogeneity" class="level3" data-number="4.4">
<h3 data-number="4.4"><span class="header-section-number">4.4</span> Descriptive Heterogeneity</h3>
<section id="cohort-profiles" class="level4" data-number="4.4.1">
<h4 data-number="4.4.1"><span class="header-section-number">4.4.1</span> Cohort Profiles</h4>
<p><a href="#fig-cohort-rank-rank" class="quarto-xref">Figure 3</a> shows that the rank-based persistence gradient differs across cohorts, even though all cohort profiles remain positive. The youngest adult cohort moves from a slope of <strong>0.184</strong> in 2010 to <strong>0.196</strong> in 2022-23, while the oldest cohort stays closer to one quarter throughout the period. These are descriptive cross-cohort differences rather than cohort effects identified from a panel.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cohort-rank-rank" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-cohort-rank-rank-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="00_main_files/figure-html/fig-cohort-rank-rank-1.png" class="img-fluid" width="672" />
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cohort-rank-rank-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 3: Rank-rank persistence by cohort and LiTS wave.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Cohort profiles are heterogeneous in levels, but they do not overturn the broader picture of substantial persistence across all waves.</p>
</section>
<section id="regional-variation" class="level4" data-number="4.4.2">
<h4 data-number="4.4.2"><span class="header-section-number">4.4.2</span> Regional Variation</h4>
<p>Regional dispersion is clearest in the rank-based measure, because the 2022 category-based regional outputs remain sparse for many origin cells. <a href="#fig-region-rank-rank" class="quarto-xref">Figure 4</a> ranks the 2022-23 regional slopes and shows a wide descriptive spread around the national slope of <strong>0.252</strong>. The highest observed persistence appears in Tashkent city at <strong>0.734</strong>, while Khorezm region sits near <strong>0.036</strong>. These regional differences are descriptive and several intervals remain wide; they indicate dispersion rather than ranked certainty.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-region-rank-rank" class="quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-region-rank-rank-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="00_main_files/figure-html/fig-region-rank-rank-1.png" class="img-fluid" width="672" />
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-region-rank-rank-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 4: Regional dispersion in the 2022-23 rank-rank slope.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Regional differences are large enough to matter for interpretation, even though the paper does not treat them as identified regional effects and several estimates remain imprecise.</p>
</section>
<section id="subgroup-split" class="level4" data-number="4.4.3">
<h4 data-number="4.4.3"><span class="header-section-number">4.4.3</span> Subgroup Split</h4>
<p><a href="#fig-upward-urban-rural" class="quarto-xref">Figure 5</a> reports the urban-rural split in category-coded upward mobility. This comparison connects directly to the pooled correlates framework, though it uses the category-based rate rather than the rank-based trend benchmark and remains descriptive.</p>
<p>The companion gender split is not promoted to the main text because the 2022-23 male category-mobility sample is only 260 with a weighted effective N of about 164.9, which makes that panel less informative than the urban-rural comparison.</p>
<div id="fig-upward-urban-rural" class="quarto-float quarto-figure quarto-figure-center" alt="Upward mobility by urban and rural residence.">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-upward-urban-rural-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../outputs/figures/tier_a_upward_by_urban_rural.png" class="img-fluid" alt="Upward mobility by urban and rural residence." />
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-upward-urban-rural-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 5: Upward mobility by urban and rural residence.
</figcaption>
</figure>
</div>
<p>Subgroup descriptives are useful for orientation, but the rank-based national series remains the most reliable summary of cross-wave mobility levels.</p>
</section>
</section>
</section>
<section id="correlates-of-educational-mobility" class="level2" data-number="5">
<h2 data-number="5"><span class="header-section-number">5</span> Correlates of Educational Mobility</h2>
<section id="pooled-persistence-trend-model" class="level3" data-number="5.1">
<h3 data-number="5.1"><span class="header-section-number">5.1</span> Pooled Persistence-Trend Model</h3>
<p>The pooled rank-based persistence models keep the same fixed-effects structure and vary only in how much additional adjustment is imposed. Across the three nested specifications, the implied conditional 2010 parent-child slope ranges from 0.140 to 0.155, the 2016 slope ranges from 0.309 to 0.309, and the 2022-23 slope ranges from 0.251 to 0.248. The substantive picture is stable across specifications: the conditional association is strongest in 2016, and the 2022-23 gradient is closer to 2016 than to a full reversal back to 2010.</p>
<p>The formal conditional tests mirror the descriptive ones, and the few-cluster sensitivity leaves the main ranking intact. <a href="#tbl-wave-diff-tests" class="quarto-xref">Table 6</a> reports the wave-difference estimates, conventional region-clustered p-values, and Webb wild-cluster-bootstrap p-values across all three specifications. The 2010-to-2016 slope increase is positive and statistically distinguishable in every specification; the 2016-to-2022 difference is negative but imprecise throughout. At best, the 2010-to-2022 contrast is suggestive in the minimal model and imprecise once demographic or extended controls are added. The pooled evidence therefore supports persistence and a mid-period strengthening more clearly than a monotonic worsening in every later wave.</p>
<div class="cell">
<div id="tbl-wave-diff-tests" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-wave-diff-tests-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 6: Conditional wave-difference tests for the persistence-trend model.
</figcaption>
<div aria-describedby="tbl-wave-diff-tests-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Comparison</th>
<th style="text-align: left;">Specification</th>
<th style="text-align: left;">Estimate</th>
<th style="text-align: left;">Cluster p</th>
<th style="text-align: left;">Bootstrap p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">2010 to 2016</td>
<td style="text-align: left;">Minimal</td>
<td style="text-align: left;">0.169</td>
<td style="text-align: left;">&lt;0.001</td>
<td style="text-align: left;">0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">2010 to 2016</td>
<td style="text-align: left;">Demographic</td>
<td style="text-align: left;">0.154</td>
<td style="text-align: left;">&lt;0.001</td>
<td style="text-align: left;">0.002</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2010 to 2016</td>
<td style="text-align: left;">Extended</td>
<td style="text-align: left;">0.154</td>
<td style="text-align: left;">0.001</td>
<td style="text-align: left;">0.002</td>
</tr>
<tr class="even">
<td style="text-align: left;">2016 to 2022</td>
<td style="text-align: left;">Minimal</td>
<td style="text-align: left;">-0.059</td>
<td style="text-align: left;">0.289</td>
<td style="text-align: left;">0.322</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2016 to 2022</td>
<td style="text-align: left;">Demographic</td>
<td style="text-align: left;">-0.061</td>
<td style="text-align: left;">0.276</td>
<td style="text-align: left;">0.313</td>
</tr>
<tr class="even">
<td style="text-align: left;">2016 to 2022</td>
<td style="text-align: left;">Extended</td>
<td style="text-align: left;">-0.061</td>
<td style="text-align: left;">0.277</td>
<td style="text-align: left;">0.313</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Notes: Estimates are slope differences from the pooled persistence-trend model (Eq. 2). Cluster p-values use region-level clustering. Bootstrap p-values use Webb wild-cluster bootstrap with 9,999 replications.</p>
</section>
<section id="attainment-score-model" class="level3" data-number="5.2">
<h3 data-number="5.2"><span class="header-section-number">5.2</span> Attainment-Score Model</h3>
<p>The attainment-score regression shows the most stable parental association in the paper. The parental education score coefficient is 0.235 in the minimal model, 0.243 after adding urban residence and female, and 0.243 in the extended specification. This stability is useful substantively because it shows that the central parental-education association is not being created by the additional current household controls.</p>
<p>Urban residence and female are background adjustment variables, while migration exposure and multigenerational household structure are current household characteristics that may themselves be shaped by education, migration, or later-life decisions. The extended specification is therefore a sensitivity layer, not a cleaner design. Parental educational background remains the strongest and most stable predictor in the pooled attainment model.</p>
</section>
<section id="raw-versus-conditional-trend-interpretation" class="level3" data-number="5.3">
<h3 data-number="5.3"><span class="header-section-number">5.3</span> Raw Versus Conditional Trend Interpretation</h3>
<p>The raw descriptive and conditional associational profiles are close. The extended conditional slopes (0.155, 0.309, 0.248) track the national raw series. Conditioning does not overturn the headline profile or suggest that the 2016 peak is purely a composition artifact.</p>
<p>The subgroup checks show that the increase is not uniform. The 2010-to-2016 rise is larger and more precisely estimated among women, rural respondents, and the 35-44 cohort than among men, urban respondents, or the oldest cohort. The rise in persistence is only partly compositional and not equally strong in every subgroup. The flatter 2016-to-2022 pattern likely reflects a combination of composition and substantive change that repeated cross-sections cannot fully separate.</p>
</section>
<section id="upward-mobility-models" class="level3" data-number="5.4">
<h3 data-number="5.4"><span class="header-section-number">5.4</span> Upward Mobility Models</h3>
<p>The upward-mobility linear probability models show that upward transitions are more common from lower starting positions on the parental education ladder. These category-based coefficients are secondary to the rank-based trend evidence. The appendix includes a low-parent-only variant as an exploratory sensitivity. Because these models are anchored to a coarse six-category ladder, they orient transition patterns, not support stronger design claims. Appendix D4 reports the full coefficient tables.</p>
</section>
<section id="heterogeneity-in-persistence" class="level3" data-number="5.5">
<h3 data-number="5.5"><span class="header-section-number">5.5</span> Heterogeneity in Persistence</h3>
<p>The same-category persistence models show a positive association between parental education score and remaining in the same category, but interaction patterns are more specification-dependent than the core rank-based results. The positive 2022 interaction in these category-based models does not overturn the rank-based reading: the strongest evidence remains a 2010-to-2016 strengthening rather than a step-up in every later wave. <a href="#tbl-pooled-correlates" class="quarto-xref">Table 7</a> summarizes the main nested parental coefficients.</p>
<div class="cell">
<div id="tbl-pooled-correlates" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pooled-correlates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 7: Nested associational estimates for the main parental coefficients.
</figcaption>
<div aria-describedby="tbl-pooled-correlates-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top">
<colgroup>
<col style="width: 21%" />
<col style="width: 16%" />
<col style="width: 29%" />
<col style="width: 10%" />
<col style="width: 12%" />
<col style="width: 9%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: left;">Specification</th>
<th style="text-align: left;">Term</th>
<th style="text-align: left;">Estimate</th>
<th style="text-align: left;">Std. Error</th>
<th style="text-align: left;">P-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Persistence trend</td>
<td style="text-align: left;">Minimal</td>
<td style="text-align: left;">Parent rank (2010 slope)</td>
<td style="text-align: left;">0.140</td>
<td style="text-align: left;">0.038</td>
<td style="text-align: left;">0.003</td>
</tr>
<tr class="even">
<td style="text-align: left;">Persistence trend</td>
<td style="text-align: left;">Minimal</td>
<td style="text-align: left;">2016 minus 2010 slope</td>
<td style="text-align: left;">0.169</td>
<td style="text-align: left;">0.046</td>
<td style="text-align: left;">0.003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Persistence trend</td>
<td style="text-align: left;">Minimal</td>
<td style="text-align: left;">2022-23 minus 2010 slope</td>
<td style="text-align: left;">0.110</td>
<td style="text-align: left;">0.064</td>
<td style="text-align: left;">0.110</td>
</tr>
<tr class="even">
<td style="text-align: left;">Attainment score</td>
<td style="text-align: left;">Minimal</td>
<td style="text-align: left;">Parent education score</td>
<td style="text-align: left;">0.235</td>
<td style="text-align: left;">0.020</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Persistence trend</td>
<td style="text-align: left;">Demographic</td>
<td style="text-align: left;">Parent rank (2010 slope)</td>
<td style="text-align: left;">0.155</td>
<td style="text-align: left;">0.041</td>
<td style="text-align: left;">0.002</td>
</tr>
<tr class="even">
<td style="text-align: left;">Persistence trend</td>
<td style="text-align: left;">Demographic</td>
<td style="text-align: left;">2016 minus 2010 slope</td>
<td style="text-align: left;">0.154</td>
<td style="text-align: left;">0.047</td>
<td style="text-align: left;">0.006</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Persistence trend</td>
<td style="text-align: left;">Demographic</td>
<td style="text-align: left;">2022-23 minus 2010 slope</td>
<td style="text-align: left;">0.093</td>
<td style="text-align: left;">0.067</td>
<td style="text-align: left;">0.187</td>
</tr>
<tr class="even">
<td style="text-align: left;">Attainment score</td>
<td style="text-align: left;">Demographic</td>
<td style="text-align: left;">Parent education score</td>
<td style="text-align: left;">0.243</td>
<td style="text-align: left;">0.021</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Persistence trend</td>
<td style="text-align: left;">Extended</td>
<td style="text-align: left;">Parent rank (2010 slope)</td>
<td style="text-align: left;">0.155</td>
<td style="text-align: left;">0.041</td>
<td style="text-align: left;">0.002</td>
</tr>
<tr class="even">
<td style="text-align: left;">Persistence trend</td>
<td style="text-align: left;">Extended</td>
<td style="text-align: left;">2016 minus 2010 slope</td>
<td style="text-align: left;">0.154</td>
<td style="text-align: left;">0.047</td>
<td style="text-align: left;">0.006</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Persistence trend</td>
<td style="text-align: left;">Extended</td>
<td style="text-align: left;">2022-23 minus 2010 slope</td>
<td style="text-align: left;">0.094</td>
<td style="text-align: left;">0.067</td>
<td style="text-align: left;">0.183</td>
</tr>
<tr class="even">
<td style="text-align: left;">Attainment score</td>
<td style="text-align: left;">Extended</td>
<td style="text-align: left;">Parent education score</td>
<td style="text-align: left;">0.243</td>
<td style="text-align: left;">0.021</td>
<td style="text-align: left;">&lt;0.001</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Notes: All specifications include region, cohort, and wave fixed effects. Standard errors are clustered at the region level. Appendix D4 reports the corresponding Webb wild-cluster-bootstrap p-values for the locked Eq. 2 wave comparisons. The minimal specification includes only the parental term and fixed effects, the demographic specification adds urban residence and female, and the extended specification adds the selected current household controls.</p>
</section>
<section id="household-support-environment-from-hbs" class="level3" data-number="5.6">
<h3 data-number="5.6"><span class="header-section-number">5.6</span> Household Support Environment from HBS</h3>
<p><a href="#tbl-hbs-context" class="quarto-xref">Table 8</a> reports supplementary HBS evidence that is used here only to characterize the household support environment around schooling, not to replace the core LiTS intergenerational estimates. Across pooled HBS 2021-2025 households, 65.7 percent had an enrolled member, 62.6 percent reported positive education spending, 14.2 percent reported tutoring, 16.3 percent had an emigrant member, and 14.8 percent received remittances; internet access is observed for 79.7 percent of households in the 2021-2024 internet module. These patterns provide context for interpretation by showing that schooling support, migration-linked resources, and connectivity constraints sit inside the same household environment as the LiTS persistence patterns. A separate companion note extends the same HBS layer descriptively across years, urban-rural settings, regions, and high-versus-low expansion groupings without introducing HBS mobility estimates.</p>
<p>The HBS linkage diagnostics in Appendix H also show why HBS remains supplementary. Under a conservative co-resident linkage rule, only 9.3 percent of HBS adults ages 25-64 are linkable, and that linked sample is materially younger and much less female than the full adult sample. HBS informs the household support environment but is not a direct substitute for the headline LiTS intergenerational estimates.</p>
<div class="cell">
<div id="tbl-hbs-context" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hbs-context-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 8: Supplementary HBS household support environment, pooled 2021-2025.
</figcaption>
<div aria-describedby="tbl-hbs-context-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top">
<colgroup>
<col style="width: 58%" />
<col style="width: 13%" />
<col style="width: 13%" />
<col style="width: 13%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Household support indicator</th>
<th style="text-align: left;">National</th>
<th style="text-align: left;">Urban</th>
<th style="text-align: left;">Rural</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Households with enrolled members</td>
<td style="text-align: left;">65.7 percent</td>
<td style="text-align: left;">63.5 percent</td>
<td style="text-align: left;">67.9 percent</td>
</tr>
<tr class="even">
<td style="text-align: left;">Households with positive education spending</td>
<td style="text-align: left;">62.6 percent</td>
<td style="text-align: left;">60.3 percent</td>
<td style="text-align: left;">64.9 percent</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Households with tutoring</td>
<td style="text-align: left;">14.2 percent</td>
<td style="text-align: left;">14.2 percent</td>
<td style="text-align: left;">14.1 percent</td>
</tr>
<tr class="even">
<td style="text-align: left;">Households with emigrant member</td>
<td style="text-align: left;">16.3 percent</td>
<td style="text-align: left;">13.2 percent</td>
<td style="text-align: left;">19.4 percent</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Households receiving remittances</td>
<td style="text-align: left;">14.8 percent</td>
<td style="text-align: left;">11.9 percent</td>
<td style="text-align: left;">17.8 percent</td>
</tr>
<tr class="even">
<td style="text-align: left;">Remittance households using remittances for education</td>
<td style="text-align: left;">19.6 percent</td>
<td style="text-align: left;">20.3 percent</td>
<td style="text-align: left;">19.1 percent</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Households with internet access</td>
<td style="text-align: left;">79.7 percent</td>
<td style="text-align: left;">79.6 percent</td>
<td style="text-align: left;">79.8 percent</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Notes: Estimates are descriptive pooled household shares from HBS 2021-2025, except internet access, which is available for 2021-2024. These indicators provide household context only and are not intergenerational mobility estimates.</p>
</section>
<section id="household-support-by-university-expansion-intensity" class="level3" data-number="5.7">
<h3 data-number="5.7"><span class="header-section-number">5.7</span> Household Support by University-Expansion Intensity</h3>
<p>The post-2017 higher-education expansion was not uniform across regions. Using an administrative panel of university admissions rates, HEI counts, and total enrollment per 1,000 youth aged 20-24 by region and academic year, regions are grouped into high-expansion and low-expansion categories based on the composite expansion index. <a href="#tbl-hbs-expansion" class="quarto-xref">Table 9</a> reports the same household support indicators split by this grouping.</p>
<div class="cell">
<div id="tbl-hbs-expansion" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hbs-expansion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 9: Household support indicators by university-expansion intensity, pooled HBS 2021-2025.
</figcaption>
<div aria-describedby="tbl-hbs-expansion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top">
<colgroup>
<col style="width: 57%" />
<col style="width: 14%" />
<col style="width: 15%" />
<col style="width: 11%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Indicator</th>
<th style="text-align: left;">Low expansion</th>
<th style="text-align: left;">High expansion</th>
<th style="text-align: left;">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Households with enrolled members</td>
<td style="text-align: left;">65.3 percent</td>
<td style="text-align: left;">66.2 percent</td>
<td style="text-align: left;">+0.9 pp</td>
</tr>
<tr class="even">
<td style="text-align: left;">Households with positive education spending</td>
<td style="text-align: left;">62.4 percent</td>
<td style="text-align: left;">62.9 percent</td>
<td style="text-align: left;">+0.5 pp</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Households with tutoring</td>
<td style="text-align: left;">17.2 percent</td>
<td style="text-align: left;">15.9 percent</td>
<td style="text-align: left;">-1.2 pp</td>
</tr>
<tr class="even">
<td style="text-align: left;">Households with emigrant member</td>
<td style="text-align: left;">18.2 percent</td>
<td style="text-align: left;">13.3 percent</td>
<td style="text-align: left;">-4.9 pp</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Households receiving remittances</td>
<td style="text-align: left;">16.7 percent</td>
<td style="text-align: left;">12.0 percent</td>
<td style="text-align: left;">-4.8 pp</td>
</tr>
<tr class="even">
<td style="text-align: left;">Remittance households using remittances for education</td>
<td style="text-align: left;">16.4 percent</td>
<td style="text-align: left;">26.1 percent</td>
<td style="text-align: left;">+9.7 pp</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Households with internet access</td>
<td style="text-align: left;">79.6 percent</td>
<td style="text-align: left;">79.7 percent</td>
<td style="text-align: left;">+0.1 pp</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Notes: Regions are classified as high- or low-expansion based on a composite index of bachelor admissions, HEI density, and total enrollment per 1,000 youth aged 20-24, drawn from official administrative records <span class="citation" data-cites="uzb_admin_he_2025">(<a href="#ref-uzb_admin_he_2025" role="doc-biblioref">Statistical Agency under the President of the Republic of Uzbekistan 2025</a>)</span>. The grouping is descriptive; these contrasts are not causal estimates of expansion effects. Remittance-for-education is conditional on being a remittance-receiving household.</p>
<div id="fig-expansion-compare" class="quarto-float quarto-figure quarto-figure-center" alt="Household support indicators by expansion-region grouping.">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-expansion-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../outputs/hbs_descriptive/figures/hbs_high_low_expansion_plot.png" class="img-fluid" alt="Household support indicators by expansion-region grouping." />
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-expansion-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure 6: Household support indicators by expansion-region grouping.
</figcaption>
</figure>
</div>
<p>The descriptive pattern is that most household support indicators are similar across expansion groups, with two exceptions: low-expansion regions have higher emigration and remittance receipt rates (by roughly 5 percentage points), while among remittance-receiving households, those in high-expansion regions allocate remittances toward education at a substantially higher rate. These patterns are consistent with a setting where migration and education investment operate as complementary household strategies, but they do not identify a causal expansion effect.</p>
</section>
</section>
<section id="pandemic-era-disruption" class="level2" data-number="6">
<h2 data-number="6"><span class="header-section-number">6</span> Pandemic-Era Disruption</h2>
<section id="sample-and-disruption-profile" class="level3" data-number="6.1">
<h3 data-number="6.1"><span class="header-section-number">6.1</span> Sample and Disruption Profile</h3>
<p>The child-module extension is deliberately kept secondary to Modules A and B. It is based on 183 respondents with a child enrolled before COVID and non-missing parental schooling. <a href="#tbl-modulec-sample" class="quarto-xref">Table 10</a> reports the sample flow.</p>
<p>Within this restricted sample, disruption and household substitution were substantial: <strong>78.3 percent</strong> report education stoppage during COVID, <strong>75.8 percent</strong> report at least one remote-learning challenge, and mothers are reported as the learning-support channel in <strong>87.0 percent</strong> of cases. Additional descriptive splits and the fragility checks for the mechanism regressions are reported in the technical appendix so that the main text remains focused on the strongest facts.</p>
<p>The bridge from Modules A and B to Module C requires one explicit caveat. Modules A and B use the harmonized max-parent measure because it is the most stable adult-sample proxy across waves. Module C instead uses mean observed parent years only to create a low-versus-high split inside the much smaller 2022-23 child-module sample; under the max-parent weighted median rule, the higher-parent comparison group collapses to 0 observations. Module C is a limited within-module contrast, not a directly comparable continuation of the main max-parent gradient.</p>
<div class="cell">
<div id="tbl-modulec-sample" class="cell quarto-float quarto-figure quarto-figure-center">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-modulec-sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table 10: LiTS IV child-module sample construction for Uzbekistan.
</figcaption>
<div aria-describedby="tbl-modulec-sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top">
<colgroup>
<col style="width: 92%" />
<col style="width: 7%" />
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Step</th>
<th style="text-align: right;">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Uzbekistan LiTS IV respondents</td>
<td style="text-align: right;">1006</td>
</tr>
<tr class="even">
<td style="text-align: left;">Respondents with child module eligibility info (q713 non-missing)</td>
<td style="text-align: right;">650</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Respondents with child enrolled pre-COVID (q713 = yes)</td>
<td style="text-align: right;">186</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mechanism sample with non-missing parental schooling</td>
<td style="text-align: right;">183</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Baseline parental-schooling median threshold (mean parent years)</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="even">
<td style="text-align: left;">Baseline low-parent-education group size (mean parent years)</td>
<td style="text-align: right;">114</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Baseline higher-parent-education group size (mean parent years)</td>
<td style="text-align: right;">69</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Notes: The flow is limited to Uzbekistan LiTS IV respondents with a child enrolled before COVID and non-missing parental schooling. Module C is descriptive and non-causal, and the appendix reports the fragile split-based logit diagnostics separately.</p>
</section>
<section id="main-module-c-takeaway" class="level3" data-number="6.2">
<h3 data-number="6.2"><span class="header-section-number">6.2</span> Main Module C Takeaway</h3>
<p>The main-text conclusion is descriptive. Under the baseline weighted median split, stoppage rates are nearly identical: <strong>78.2 percent</strong> among children from lower-parent-education households versus <strong>78.0 percent</strong> among those from higher-parent-education households. Together with the high overall disruption rates, this supports a practical reading centered on widespread household learning constraints rather than a precise adjusted parent-gap effect.</p>
<p>Appendix fragility diagnostics explain why adjusted split-based coefficients are not used as headline evidence. Under the strict <span class="math inline">\(\leq 9\)</span> split, the low-parent-education group falls to <strong>7</strong> observations (vs <strong>176</strong> in the comparison group), yielding a degenerate-support scenario (degenerate_low_group_support). Under the weighted median split with the project-wide max-parent proxy, the higher-parent group falls to <strong>0</strong> observations. Module C contributes suggestive descriptive evidence on household vulnerability and learning support — not a stable adjusted parental-education gradient and not causal evidence on pandemic mechanisms.</p>
</section>
</section>
<section id="discussion-and-conclusion" class="level2" data-number="7">
<h2 data-number="7"><span class="header-section-number">7</span> Discussion and Conclusion</h2>
<p>Three findings stand out.</p>
<p>Uzbekistan exhibits substantial intergenerational educational persistence, and the parent-child gradient strengthened between 2010 and 2016. The pooled associational models reproduce that mid-period shift across all three nested specifications, suggesting it is not an artifact of the fixed-effects structure or the particular set of controls included.</p>
<p>Parental education is the most consistent predictor in the pooled correlates models. The main attainment association changes little when the specification moves from parental education alone to demographic adjustment and then to extended household controls. Migration exposure and multigenerational household structure add little explanatory power once region, cohort, and wave effects are absorbed; those variables may themselves be shaped by education and later-life decisions, so they should not be given a causal reading.</p>
<p>The pandemic mechanism evidence from the child module establishes the scale of household disruption and maternal substitution more clearly than it establishes a parental-education gradient in education stoppage. Device sharing, unreliable internet, and time constraints were common across households. Mothers carried the support burden overwhelmingly.</p>
<p>As noted in the Introduction, the Uzbekistan slopes fall in the moderate-to-high range for developing countries, comparable to other post-Soviet economies and to patterns in Turkey and middle-income settings where educational expansion coexists with durable family-background gradients at upper schooling levels <span class="citation" data-cites="aydemir_yazici_2019 narayan_etal_2018">(<a href="#ref-aydemir_yazici_2019" role="doc-biblioref">Aydemir and Yazici 2019</a>; <a href="#ref-narayan_etal_2018" role="doc-biblioref">Narayan et al. 2018</a>)</span>. Part of the 2010-to-2016 increase may reflect measurement improvement; the 2010 wave uses a different parental-education question format and has substantially higher missingness. The sensitivity bounds preserve the qualitative wave ordering. LiTS also does not observe families who emigrated from Uzbekistan; if educationally selective emigration differs by family background, the persistence profile may not fully generalize. Some 2022-23 subgroup estimates and the child-module extension remain fragile, so disaggregated comparisons should be treated as indicative rather than definitive.</p>
<p>These findings point to three policy priorities. First, reducing the dependence of educational attainment on parental background: earlier remedial support, stronger transitions across schooling stages, and wider access to quality secondary and post-secondary pathways. Second, addressing spatial and household bottlenecks directly: local infrastructure, service access, and household support conditions appear to constrain mobility even where formal access has expanded. Third, strengthening household support capacity during disruptions. The child module shows that digital inclusion involves connection quality, device availability, and adults’ ability to help children learn, not only nominal internet access. Education policy that treats home-based adjustment as costless to households underestimates the burden that mothers absorb.</p>
<p>Future work could strengthen these findings through panel data that tracks families over time, administrative education records that avoid retrospective reporting error, or quasi-experimental evaluation of specific reforms in the post-2017 expansion cycle.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="bibliography" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-akarcay_polat_2017" class="csl-entry" role="listitem">
Akarçay-Gürbüz, Asli, and Seher Polat. 2017. <span>“Schooling Opportunities and Intergenerational Educational Mobility in <span>T</span>urkey.”</span> Working Paper. Piri Reis University; Yildiz Technical University.
</div>
<div id="ref-alam_tiwari_2020" class="csl-entry" role="listitem">
Alam, Andaleeb, and Priyanka Tiwari. 2020. <span>“Putting the <span>‘Learning’</span> Back in Remote Learning.”</span> UNICEF Office of Global Insight; Policy. <a href="https://www.unicef.org/globalinsight/media/1086/file/UNICEF-Global-Insight-remote-learning-issue-brief-2020.pdf">https://www.unicef.org/globalinsight/media/1086/file/UNICEF-Global-Insight-remote-learning-issue-brief-2020.pdf</a>.
</div>
<div id="ref-aydemir_yazici_2019" class="csl-entry" role="listitem">
Aydemir, Abdurrahman B., and Huseyin Yazici. 2019. <span>“Intergenerational Education Mobility and the Level of Development: Evidence from <span>T</span>urkey.”</span> <em>European Economic Review</em> 116: 160–85. <a href="https://doi.org/10.1016/j.euroecorev.2019.04.003">https://doi.org/10.1016/j.euroecorev.2019.04.003</a>.
</div>
<div id="ref-bruck_esenaliev_2018" class="csl-entry" role="listitem">
Brück, Tilman, and Damir Esenaliev. 2018. <span>“Post-Socialist Transition and Intergenerational Educational Mobility in <span>K</span>yrgyzstan.”</span> <em>Economics of Transition</em> 26 (1): 61–89. <a href="https://doi.org/10.1111/ecot.12136">https://doi.org/10.1111/ecot.12136</a>.
</div>
<div id="ref-chetty_etal_2014" class="csl-entry" role="listitem">
Chetty, Raj, Nathaniel Hendren, Patrick Kline, and Emmanuel Saez. 2014. <span>“Where Is the Land of Opportunity? <span>The</span> Geography of Intergenerational Mobility in the <span>United States</span>.”</span> <em>The Quarterly Journal of Economics</em> 129 (4): 1553–623. <a href="https://doi.org/10.1093/qje/qju022">https://doi.org/10.1093/qje/qju022</a>.
</div>
<div id="ref-emran_shilpi_2015" class="csl-entry" role="listitem">
Emran, M. Shahe, and Forhad Shilpi. 2015. <span>“Gender, Geography, and Generations: Intergenerational Educational Mobility in Post-Reform <span>India</span>.”</span> <em>World Development</em> 72: 362–80. <a href="https://doi.org/10.1016/j.worlddev.2015.03.009">https://doi.org/10.1016/j.worlddev.2015.03.009</a>.
</div>
<div id="ref-hertz_2008" class="csl-entry" role="listitem">
Hertz, Tom, Tamara Jayasundera, Patrizio Piraino, Sibel Selcuk, Nicole Smith, and Alina Verashchagina. 2008. <span>“The Inheritance of Educational Inequality: International Comparisons and Fifty-Year Trends.”</span> <em>The B.E. Journal of Economic Analysis &amp; Policy</em> 7 (2). <a href="https://doi.org/10.2202/1935-1682.1775">https://doi.org/10.2202/1935-1682.1775</a>.
</div>
<div id="ref-iqbal_patrinos_2025" class="csl-entry" role="listitem">
Iqbal, Syedah Aroob, and Harry Anthony Patrinos. 2025. <span>“Learning During the Pandemic: Evidence from <span>U</span>zbekistan.”</span> <em>Prospects</em>. <a href="https://doi.org/10.1007/s11125-025-09736-w">https://doi.org/10.1007/s11125-025-09736-w</a>.
</div>
<div id="ref-munoz_najar_etal_2021" class="csl-entry" role="listitem">
Muñoz-Najar, Alberto, Alison Gilberto, Amer Hasan, Cristobal Cobo, João Pedro Azevedo, and Maryam Akmal. 2021. <span>“Remote Learning During <span>COVID</span>-19: Lessons from Today, Principles for Tomorrow.”</span> World Bank. <a href="https://documents.worldbank.org/en/publication/documents-reports/documentdetail/160271637074230077/remote-learning-during-covid-19-lessons-from-today-principles-for-tomorrow">https://documents.worldbank.org/en/publication/documents-reports/documentdetail/160271637074230077/remote-learning-during-covid-19-lessons-from-today-principles-for-tomorrow</a>.
</div>
<div id="ref-narayan_etal_2018" class="csl-entry" role="listitem">
Narayan, Ambar, Roy van der Weide, Alexandru Cojocaru, Christoph Lakner, Silvia Redaelli, Daniel Gerszon Mahler, Rakesh Gupta N. Ramasubbaiah, and Stefan Thewissen. 2018. <em>Fair Progress?: Economic Mobility Across Generations Around the World</em>. Equity and Development. Washington, DC: World Bank. <a href="https://hdl.handle.net/10986/28428">https://hdl.handle.net/10986/28428</a>.
</div>
<div id="ref-uzb_admin_he_2025" class="csl-entry" role="listitem">
Statistical Agency under the President of the Republic of Uzbekistan. 2025. <span>“Official Higher Education Administrative Series for Uzbekistan, Academic Years 2019/20–2024/25.”</span>
</div>
<div id="ref-stromberg_engzell_2025" class="csl-entry" role="listitem">
Strömberg, Ely, and Per Engzell. 2025. <span>“How Robust Are Country Rankings in Educational Mobility?”</span> <em>Sociological Science</em> 12: 891–922. <a href="https://doi.org/10.15195/v12.a36">https://doi.org/10.15195/v12.a36</a>.
</div>
<div id="ref-torche_2015" class="csl-entry" role="listitem">
Torche, Florencia. 2015. <span>“Intergenerational Mobility and Equality of Opportunity.”</span> <em>Archives Europ<span>é</span>ennes de Sociologie</em> 56 (3): 343–71. <a href="https://doi.org/10.1017/S0003975615000181">https://doi.org/10.1017/S0003975615000181</a>.
</div>
<div id="ref-unicef_compact_2024" class="csl-entry" role="listitem">
UNICEF. 2024. <span>“Partnership Compact for Education Reform.”</span> UNICEF Uzbekistan. <a href="https://www.unicef.org/uzbekistan/en/reports/partnership-compact-education-reform">https://www.unicef.org/uzbekistan/en/reports/partnership-compact-education-reform</a>.
</div>
<div id="ref-unicef_sitan_2020" class="csl-entry" role="listitem">
UNICEF Uzbekistan. 2020. <span>“Situation Analysis of Children in <span>U</span>zbekistan 2019/2020.”</span> UNICEF Uzbekistan. <a href="https://www.unicef.org/uzbekistan/en/press-releases/unicef-launches-situation-analysis-uzbekistan-children-and-warns-covid-19-pandemic">https://www.unicef.org/uzbekistan/en/press-releases/unicef-launches-situation-analysis-uzbekistan-children-and-warns-covid-19-pandemic</a>.
</div>
<div id="ref-unicef_sitan_2024" class="csl-entry" role="listitem">
———. 2024. <span>“Situation Analysis of Children and Adolescents in <span>U</span>zbekistan.”</span> UNICEF Uzbekistan. <a href="https://www.unicef.org/uzbekistan/en/reports/situation-analysis-children-and-adolescents-uzbekistan">https://www.unicef.org/uzbekistan/en/reports/situation-analysis-children-and-adolescents-uzbekistan</a>.
</div>
<div id="ref-urbina_2018" class="csl-entry" role="listitem">
Urbina, Daniela R. 2018. <span>“Intergenerational Educational Mobility During Expansion Reform: Evidence from <span>M</span>exico.”</span> <em>Population Research and Policy Review</em> 37 (3): 367–417. <a href="https://doi.org/10.1007/s11113-018-9466-4">https://doi.org/10.1007/s11113-018-9466-4</a>.
</div>
<div id="ref-verashchagina_2012" class="csl-entry" role="listitem">
Verashchagina, Alina. 2012. <span>“Education and Socioeconomic Mobility in Post-Communist Countries.”</span> In <em>Social Exclusion: Short and Long-Term Causes and Consequences</em>, edited by Giuliana Parodi and Dario Sciulli. AIEL Series in Labour Economics. Heidelberg: Springer.
</div>
<div id="ref-weide_etal_2024" class="csl-entry" role="listitem">
Weide, Roy van der, Christoph Lakner, Daniel Gerszon Mahler, Ambar Narayan, and Rakesh Gupta. 2024. <span>“Intergenerational Mobility Around the World: A New Database.”</span> <em>Journal of Development Economics</em> 166: 103167. <a href="https://doi.org/10.1016/j.jdeveco.2023.103167">https://doi.org/10.1016/j.jdeveco.2023.103167</a>.
</div>
<div id="ref-wb_modernizing_tertiary_2017" class="csl-entry" role="listitem">
World Bank. 2017. <span>“Uzbekistan: Modernizing Tertiary Education.”</span> World Bank. <a href="https://hdl.handle.net/10986/27992">https://hdl.handle.net/10986/27992</a>.
</div>
<div id="ref-wb_uzb_2018" class="csl-entry" role="listitem">
———. 2018. <span>“Uzbekistan Education Sector Analysis.”</span> AUS0000586. World Bank. <a href="https://documents.worldbank.org/en/publication/documents-reports/documentdetail/648681587857648494/uzbekistan-education-sector-analysis-final-report">https://documents.worldbank.org/en/publication/documents-reports/documentdetail/648681587857648494/uzbekistan-education-sector-analysis-final-report</a>.
</div>
<div id="ref-wb_gender_2024" class="csl-entry" role="listitem">
———. 2024. <span>“Country Gender Assessment: <span>U</span>zbekistan.”</span> World Bank. <a href="https://thedocs.worldbank.org/en/doc/752717e92c8ad1476bc6cb007bae8f1a-0080012024/original/uz-country-gender-assessment-2024-uz-pdf.pdf">https://thedocs.worldbank.org/en/doc/752717e92c8ad1476bc6cb007bae8f1a-0080012024/original/uz-country-gender-assessment-2024-uz-pdf.pdf</a>.
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id = "quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->

</body>

</html>
